### ISSUE TITLE
Issue with generate_multihetsep.py

### ISSUE THREAD

**Issue by angelesdecara** [stschiff/msmc-tools#24]
Dear Stephan and whoever can help,

In the past (i.e., over one year ago), I have used successfully generate_multihetsep.py successfully. However, for the last month, I keep getting this error:

generating msmc input file with 2 haplotypes
Traceback (most recent call last):
  File "./generate_multihetsep.py", line 213, in <module>
    for chrom, snp_pos, alleles in joinedVcfIterator:
  File "./generate_multihetsep.py", line 147, in __next__
    self.current_lines[i] = next(self.vcfIterators[i])
  File "./generate_multihetsep.py", line 75, in __next__
    return (chrom, pos, tuple(alleles), (int(geno[0]), int(geno[2])), phased)
ValueError: invalid literal for int() with base 10: '.'

I get the same error with and without a mask, and from my little understanding of python I cannot figure out which column in the vcf file is different to what generate_multihetsep.py
All help will be hugely appreciated while I dig into old files.

**Comment by angelesdecara** [comment]
Sorted, I think: I had to remove missing data.
